"""Report generation — self-contained HTML race reports (no heavy deps).

Produces an F1-themed standalone HTML file with the predicted result, probabilities and a
Monte Carlo summary. WeasyPrint (optional ``report`` extra) can convert it to PDF, but the
HTML is fully usable on its own.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from ..config import Config, load_config

_CSS = """
body{background:#0D0D0D;color:#F5F5F5;font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:32px;}
h1{color:#E10600;letter-spacing:1px;} h2{border-left:4px solid #E10600;padding-left:10px;}
table{border-collapse:collapse;width:100%;margin:16px 0;}
th{background:#E10600;color:#fff;padding:8px;text-align:left;}
td{padding:8px;border-bottom:1px solid #222;}
tr:nth-child(even){background:#151515;}
.bar{display:inline-block;height:10px;background:#E10600;border-radius:3px;}
.card{background:#151515;border:1px solid #222;border-radius:8px;padding:16px;margin:8px 0;}
"""


def _prob_cell(p: float) -> str:
    return f'<span class="bar" style="width:{int(p*100)}px"></span> {p:.1%}'


def build_race_report(
    cfg: Config | None = None,
    season: int | None = None,
    rnd: int | None = None,
    output: str = "reports/race_report.html",
    n_sim: int = 10000,
) -> Path:
    cfg = cfg or load_config()
    from ..data_pipeline import load_master
    from ..models import load_production
    from ..simulation import simulate_race
    from ..whatif import get_feature_frame, get_race, upcoming_race

    df = load_master(cfg)
    feat_df, _ = get_feature_frame(df, cfg)
    if season is None or rnd is None:
        season, rnd = upcoming_race(feat_df)
    race = get_race(feat_df, season, rnd)
    pred = load_production(cfg)
    tbl = pred.predict_race(race, season=season)
    sim = simulate_race(race, pred.predict_positions(race), pred.residual_std,
                        n_sim=n_sim, season=season, cfg=cfg)
    sim_frame = sim.to_frame()

    race_name = race["race_name"].iloc[0]
    rows = ""
    for i, r in enumerate(tbl.itertuples(), start=1):
        rows += (f"<tr><td>{i}</td><td>{r.driver_name}</td><td>{r.constructor_name}</td>"
                 f"<td>{int(r.grid)}</td><td>{_prob_cell(r.p_win)}</td>"
                 f"<td>{_prob_cell(r.p_podium)}</td><td>{r.expected_points:.1f}</td></tr>")
    top = sim_frame.iloc[0]
    html = f"""<!doctype html><html><head><meta charset="utf-8">
<title>f1predict — {race_name} {season}</title><style>{_CSS}</style></head><body>
<h1>f1predict</h1>
<div class="card"><h2>{race_name} {season} · Round {rnd}</h2>
<p>Model favourite: <b>{top.driver_name}</b> — P(win) {top.p_win:.1%}, P(podium) {top.p_podium:.1%}.
Based on {n_sim:,} Monte Carlo simulations.</p></div>
<h2>Predicted Result</h2>
<table><tr><th>#</th><th>Driver</th><th>Team</th><th>Grid</th>
<th>P(win)</th><th>P(podium)</th><th>xPts</th></tr>{rows}</table>
<p style="color:#666">Generated by f1predict · model family: {pred.family}</p>
</body></html>"""

    path = Path(output)
    if not path.is_absolute():
        path = cfg.path("paths.reports_dir") / path.name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html)
    return path
